### PR TITLE
Master

### PR DESCRIPTION
**Pull request by WeisTekEng**
added display on energy page for uptime. Allows user to keep track of test time. also moved the voltage and current text down one pixel space.

### CODE REVIEW

**Comment by FriedCircuits** [comment]
Looks like line 135 isn't needed. Also Arduino doesn't need 114 either. Then I can commit and update firmware version and reset function. Thanks for the pull.

**Comment by WeisTekEng** [comment]
will add the pull request soon, computer ran out of ram and my IDE borked
itself.

On Thu, Jun 23, 2016 at 9:52 PM, William <notifications@github.com> wrote:

> Looks like line 135 isn't needed. Also Arduino doesn't need 114 either.
> Then I can commit and update firmware version and reset function. Thanks
> for the pull.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FriedCircuits/FC-USB-Tester-OLED-Backpack/pull/7#issuecomment-228257703>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ0MLO4v0yLfEM9RFaqsK-wsY82wyxG_ks5qO2J0gaJpZM4I9dM7>
> .
>



-- 
WeisTek Engineering
www.WeisTekEngineeing.com
Jeremy G

**Comment by WeisTekEng** [comment]
new pull request sent.

On Thu, Jun 23, 2016 at 9:58 PM, Jeremy G <ocybress@gmail.com> wrote:

> will add the pull request soon, computer ran out of ram and my IDE borked
> itself.
>
> On Thu, Jun 23, 2016 at 9:52 PM, William <notifications@github.com> wrote:
>
>> Looks like line 135 isn't needed. Also Arduino doesn't need 114 either.
>> Then I can commit and update firmware version and reset function. Thanks
>> for the pull.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/FriedCircuits/FC-USB-Tester-OLED-Backpack/pull/7#issuecomment-228257703>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AJ0MLO4v0yLfEM9RFaqsK-wsY82wyxG_ks5qO2J0gaJpZM4I9dM7>
>> .
>>
>
>
>
> --
> WeisTek Engineering
> www.WeisTekEngineeing.com
> Jeremy G
>
>


-- 
WeisTek Engineering
www.WeisTekEngineeing.com
Jeremy G

**Comment by FriedCircuits** [comment]
Do you think it looks bad with the graph overlapping the run time text on the graph view?

**Comment by WeisTekEng** [comment]
I didn't get the current spikes that high, you got a pic?

**Comment by FriedCircuits** [comment]
usb_tester_run_time_graph

**Comment by FriedCircuits** [comment]
It is just enough before the auto scale kicks in.

**Comment by WeisTekEng** [comment]
Can you lower the auto scale threshold?

**Comment by FriedCircuits** [comment]
I could but wouldn't that reduce the usable area of the display?

**Comment by WeisTekEng** [comment]
Ah, I would have to see how that's implemented. Calming a screaming baby
atm. Then I look at it. If it becomes too obtrusive then you can prolly
just get away with it on the other two pages.

**Comment by FriedCircuits** [comment]
Hmm... Most of the time its okay. I was measuring the $9 CHIP once it passed 500mA it scaled and now its fine sitting at ~533mA at the desktop

**Comment by WeisTekEng** [comment]
Mmm, it may be fine for momentary spikes, people may not care or even
notice it. But if it stays there cutting the time it may annoy some people.

**Comment by WeisTekEng** [comment]
Looks like line 510 at the end the int 54 is the upper (or lower?) limit of
the screen if you offset this post by 7 then your graph should stop
overlapping the time and scale display.

**Comment by FriedCircuits** [comment]
This has been added to FW 2.3+. Thank you for the contribution!

**Pull request closed without merging**
